services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: Anil@123456
      MYSQL_DATABASE: testdb
      MYSQL_USER: anil
      MYSQL_PASSWORD: Anil@123456
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      mern-app:
        ipv4_address: 192.168.100.10

  express:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: express-server
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-server
      DB_USER: anil
      DB_PASSWORD: Anil@123456
      DB_NAME: testdb
      DB_PORT: 3306
    ports:
      - "5000:5000"  # Expose Express API
    command: >
      /bin/sh -c "
        until nc -z mysql-server 3306; do
          echo '⏳ Waiting for MySQL...';
          sleep 2;
        done;
        echo '✅ MySQL is up - starting server';
        yarn start
      "
    networks:
      mern-app:
        ipv4_address: 192.168.100.20

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client
    depends_on:
      - express
    environment:
      - REACT_APP_API_BASE_URL=http://nginx-proxy/api
    ports:
      - "3000:5173"
    networks:
      mern-app:
        ipv4_address: 192.168.100.30

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - express
      - client
    networks:
      mern-app:
        ipv4_address: 192.168.100.40

volumes:
  mysql-data:

networks:
  mern-app:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1

